UserIDays/UserIDays/Models/Converters/IConverter.cs
namespace UserIDays.Models.Converters
{
    using System.Threading.Tasks;

    public interface IConverter<in T, T1> where T1 : IModelResult
    {
        Task<T1> Convert(T input);
    }
}

UserIDays/UserIDays/Models/Converters/UserDetailsViewModelConverter.cs
namespace UserIDays.Models.Converters
{
    using System.Threading.Tasks;
    using FluentValidation;
    using UserDetail;
    using View;

    internal class UserDetailsViewModelConverter : IConverter<UserDetailsViewModel, ModelResult<UserDetail, UserConvertionStatus>>
    {
        private readonly IValidator _userDetailsValidator;

        public UserDetailsViewModelConverter(IValidator userDetailsValidator)
        {
            _userDetailsValidator = userDetailsValidator;
        }

        public async Task<ModelResult<UserDetail, UserConvertionStatus>> Convert(UserDetailsViewModel input)
        {
            var validationResult = await _userDetailsValidator.ValidateAsync(input);

            if(!validationResult.IsValid)
                return new ModelResult<UserDetail, UserConvertionStatus>(UserDetail.Null, UserConvertionStatus.Invalid);

            var userDetail = new UserDetail(input.Email, input.Password);

            return new ModelResult<UserDetail, UserConvertionStatus>(userDetail, UserConvertionStatus.Valid); ;
        }
    }
}

UserIDays/UserIDays/Models/ErrorViewModel.cs
namespace UserIDays.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UserIDays/UserIDays/Models/IModelResult.cs
namespace UserIDays.Models
{
    public interface IModelResult
    {

    }
}

UserIDays/UserIDays/Models/ModelResult.cs
namespace UserIDays.Models
{
    public class ModelResult<T, T1> : IModelResult where T : class
    {
        public T Result { get; }
        public T1 Status { get; }

        public ModelResult(T result, T1 status)
        {
            Result = result;
            Status = status;
        }
    }
}

UserIDays/UserIDays/Models/Password/PasswordHash.cs
namespace UserIDays.Models.Password
{
    public class PasswordHash
    {
        public string Salt { get; }
        public string HashedPassword { get; }
        
        public PasswordHash(string salt, string hashedPassword)
        {
            Salt = salt;
            HashedPassword = hashedPassword;
        }
    }
}

UserIDays/UserIDays/Models/UserDetail/UserConvertionStatus.cs
namespace UserIDays.Models.UserDetail
{
    public enum UserConvertionStatus
    {
        Valid = 0,
        Invalid = 1
    }
}

UserIDays/UserIDays/Models/UserDetail/UserDetails.cs
namespace UserIDays.Models.UserDetail
{
    using System;

    public class UserDetail
    {
        public string Email { get; }
        public string Password { get; }

        public UserDetail(string email, string password)
        {
            Email = email;
            Password = password;
        }

        public static readonly NullUserDetail Null = NullUserDetail;

        private static NullUserDetail NullUserDetail
        {
            get
            {
                return new NullUserDetail();
            }
        }
    }

    public class NullUserDetail : UserDetail
    {
        public NullUserDetail() : base(String.Empty, String.Empty)
        {
        }
    }
}

UserIDays/UserIDays/Models/View/UserDetailsViewModel.cs
namespace UserIDays.Models.View
{
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Mvc;

    public class UserDetailsViewModel
    {
        [FromForm]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [FromForm]
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

UserIDays/UserIDays/Controllers/RegisterController.cs
namespace UserIDays.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Models.Converters;
    using Models.UserDetail;
    using Models.View;
    using Services.User;

    public class RegisterController : Controller
    {
        private readonly IConverter<UserDetailsViewModel, ModelResult<UserDetail, UserConvertionStatus>> _modelConverter;
        private IUserService _userService;


        public RegisterController(IConverter<UserDetailsViewModel, ModelResult<UserDetail, UserConvertionStatus>> modelConverter,
                                  IUserService userService)
        {
            _userService = userService;
            _modelConverter = modelConverter;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Index(UserDetailsViewModel userDetailsViewModel)
        {
            if (!ModelState.IsValid)
            {
                userDetailsViewModel.Password = null;

                if(ModelState["Password"].Errors.Count > 0)
                    ModelState.AddModelError("PasswordError", "Invalid password");

                if (ModelState["Email"].Errors.Count > 0)
                    ModelState.AddModelError("EmailError", "Invalid password");

                return View(userDetailsViewModel);
            }

            var userDetailsResult = await _modelConverter.Convert(userDetailsViewModel);

            if (userDetailsResult.Status == UserConvertionStatus.Invalid)
            {
                userDetailsViewModel.Password = null;

                ModelState.AddModelError("PasswordError", "Invalid password");

                return View(userDetailsViewModel);
            }

            await _userService.Create(userDetailsResult.Result);

            return View();
        }
    }
}

UserIDays/UserIDays/Views/Register/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@using UserIDays.Models.View
@model UserDetailsViewModel

<div class="container is-fluid">
    <div class="header is-size-1">Register</div>
    <form id="frmRegister" asp-action="Index" asp-controller="Register">
        <div class="field">
            <label class="label">Email</label>
            <div class="control has-icons-left has-icons-right">
                <input class="input is-primary" type="email" placeholder="Email" asp-for="Email">
                <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>
                @if (ViewData.ModelState.ContainsKey("EmailError"))
                {
                    <span class="icon is-small is-right">
                        <i class="fas fa-exclamation-triangle"></i>
                    </span>

                    <p class="help is-danger">This email is invalid</p>
                }
            </div>
        </div>

        <div class="field">
            <label class="label">Password</label>
            <div class="control has-icons-left has-icons-right">
                <input class="input is-primary" type="password" placeholder="Password" asp-for="Password">
                <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                </span>
                <p class="help">Min 10, Max 128 and No < > characters</p>
                @if (ViewData.ModelState.ContainsKey("PasswordError"))
                {
                    <span class="icon is-small is-right">
                        <i class="fas fa-exclamation-triangle"></i>
                    </span>

                    <p id="txtInvalidPassword" class="help is-danger">This password is invalid</p>
                }
            </div>
        </div>
        <input id="btnRegister" class="button is-link is-focused" type="submit" value="Register">
    </form>
</div>

UserIDays/UserIDays/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LogNiDays</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    </environment>
</body>
</html>